// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU7DfNgPtK9_2FoelY-Ho3sWd1ZYlRsNM',
    appId: '1:964462171692:web:e38d361574d612bda4a389',
    messagingSenderId: '964462171692',
    projectId: 'kunhii-daf8a',
    authDomain: 'kunhii-daf8a.firebaseapp.com',
    storageBucket: 'kunhii-daf8a.firebasestorage.app',
    measurementId: 'G-ZBVT2KHG10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSzi85WOXg8xZjq6N4LOaV-g7YaYNGw8k',
    appId: '1:964462171692:android:69b1e03c74c27c42a4a389',
    messagingSenderId: '964462171692',
    projectId: 'kunhii-daf8a',
    storageBucket: 'kunhii-daf8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwypdhI5gK2FHHX13LTEncy_XlkmNfxS0',
    appId: '1:964462171692:ios:c2da9a4b1a8bf609a4a389',
    messagingSenderId: '964462171692',
    projectId: 'kunhii-daf8a',
    storageBucket: 'kunhii-daf8a.firebasestorage.app',
    iosBundleId: 'com.example.kunhii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwypdhI5gK2FHHX13LTEncy_XlkmNfxS0',
    appId: '1:964462171692:ios:c2da9a4b1a8bf609a4a389',
    messagingSenderId: '964462171692',
    projectId: 'kunhii-daf8a',
    storageBucket: 'kunhii-daf8a.firebasestorage.app',
    iosBundleId: 'com.example.kunhii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU7DfNgPtK9_2FoelY-Ho3sWd1ZYlRsNM',
    appId: '1:964462171692:web:95fef4687bd555f5a4a389',
    messagingSenderId: '964462171692',
    projectId: 'kunhii-daf8a',
    authDomain: 'kunhii-daf8a.firebaseapp.com',
    storageBucket: 'kunhii-daf8a.firebasestorage.app',
    measurementId: 'G-9GBB1Y1X8Z',
  );
}
